# fly.toml app configuration file generated for grammar-correction on 2025-10-28T21:30:00Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "grammar-correction"
primary_region = "iad"

[build]

[env]
  PORT = "8000"
  REDIS_HOST = "localhost"
  REDIS_PASSWORD = "BigDrops@9991"
  ALLOWED_ORIGINS = "*"
  FLOWER_USER = "admin"
  FLOWER_PASSWORD = "BigDrops@9991"
  PYTHON_VERSION = "3.11"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/health"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[deploy]
  release_command = "echo 'Deployment completed successfully'"
