global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'grammar-correction-api'
    environment: 'production'

# Alerting configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Rule files
rule_files:
  # - "alerts.yml"

# Scrape configurations
scrape_configs:
  # FastAPI application metrics
  - job_name: 'grammar-api'
    static_configs:
      - targets: ['api:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 15s

  # Nginx metrics
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    metrics_path: '/nginx-health'
    scrape_interval: 15s

  # Celery worker metrics
  - job_name: 'celery-workers'
    static_configs:
      - targets: ['worker:8000']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # Flower metrics
  - job_name: 'flower'
    static_configs:
      - targets: ['flower:5555']
    scrape_interval: 30s

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

