apiVersion: v1
kind: ConfigMap
metadata:
  name: grammar-config
  namespace: grammar-correction
data:
  # Environment
  ENVIRONMENT: "production"
  DEBUG: "false"
  
  # Application Settings
  APP_NAME: "Grammar Correction API"
  APP_VERSION: "1.0.0"
  API_HOST: "0.0.0.0"
  API_PORT: "8000"
  API_WORKERS: "4"
  
  # Redis Configuration
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  
  # Model Settings
  MODEL_PATH: "/app/model"
  MODEL_MAX_LENGTH: "128"
  MODEL_NUM_BEAMS: "5"
  
  # OCR Settings
  OCR_LANGUAGES: '["en"]'
  OCR_CONFIDENCE_THRESHOLD: "0.5"
  
  # Processing Settings
  MAX_FILE_SIZE: "10485760"
  ALLOWED_IMAGE_EXTENSIONS: '[".jpg", ".jpeg", ".png"]'
  ALLOWED_HTML_EXTENSIONS: '[".html", ".htm"]'
  CONTEXT_WORDS: "3"
  
  # Cache Settings
  CACHE_TTL: "3600"
  ENABLE_CACHING: "true"
  
  # Monitoring
  ENABLE_METRICS: "true"
  FLOWER_PORT: "5555"
  FLOWER_USER: "admin"
  
  # CORS Settings - UPDATE THESE WITH YOUR ACTUAL DOMAINS
  ALLOWED_ORIGINS: "*"
  CORS_ALLOW_CREDENTIALS: "true"
  CORS_ALLOW_METHODS: '["GET", "POST", "PUT", "DELETE", "OPTIONS"]'
  CORS_ALLOW_HEADERS: '["*"]'
  
  # Additional Settings
  ALLOWED_ARCHIVE_EXTENSIONS: '[".zip"]'
  MAX_ZIP_EXTRACT_SIZE: "52428800"
  MAX_FILES_IN_ZIP: "100"